### ISSUE TITLE
Arguments to chained functions are moved to new lines

### ISSUE THREAD

**Issue by alinnow** [ahungry/prog-fill#4]
After installing version 20180128.2019 in emacs 25.3.1, I wanted to use this in js2-mode, but it doesn't work as documented/expected.

Using the example in the readme:

```js
superagent.get(someUrl).then(response => response.body).catch(reason => console.log(reason))
```

becomes 

```js
superagent.get(
  someUrl
)
  .then(
    response => response.body
  )
  .catch(
    reason => console.log(
      reason
    )
  )
```

but I would like it to look the the example in the readme:

```js
superagent.get(someUrl)
  .then(response => response.body)
  .catch(reason => console.log(reason))
```

I looked at the configuration options and there doesn't seem to be an option for this kind of filling, unless perhaps I misunderstood something.

If it helps, you can see which other packages I am using here: https://github.com/alanpearce/dotfiles/blob/master/emacs/.emacs.d/main.el

**Comment by ahungry** [comment]
There's two floating parenthesis defcustoms, try setting both to nil.

ill update the readme to list current config under each sample.

**Comment by alinnow** [comment]
Ah yes. I saw them, but it didn't click that setting both would do this. Thanks, it works.
